### PR TITLE
feat: add role admin and fix router

### LINKED ISSUE #50: Thêm role admin + cấu hình lại Vue Router

### PR DESCRIPTION
**Pull request by ductt-3362**

### CODE REVIEW

File: src/components/PagiNation.vue [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+      </template>
+      <!--If the number of pages is greater than 3, 
+      only the first and last pages are displayed and 1 page before and after the current page. -->
+      <template v-else>
+        <li
+          v-if="currentIndex > numItems + 1"
+          @click="handlePaginate(1)"
+          :class="[getStylePageActive(1), pageIndexStyle]"
+        >
+          {{ 1 }}
```
Comment (anhdd-3363) [inline src/components/PagiNation.vue]: @ductt-3362 remove ```{{ }}```

File: src/apis/comment.js [hunk 2]
```diff
@@ -0,0 +1,8 @@
+import { api } from "./axios";
+export const getCommentApi = async (bookId, params) =>
```
Comment (anhdd-3363) [inline src/apis/comment.js]: @ductt-3362 suggest rename ```getCommentsApi```
